### ISSUE TITLE
request: Install / Usage guide

### ISSUE THREAD

**Issue by gyaresu** [polygon/spectrum_painter#1]
A quick 'getting started' section in the readme with install and example usage commands.

**Comment by polygon** [comment]
Added usage examples to the README file. Can you get it to work?

**Comment by gyaresu** [comment]
You, dear person are a champion. 

I won't have access to my HackRF's until tonight but I absolutely will feedback as soon as possible.

That excellent documentation helps immensely to get started.

(particularly the trick with pip)

Thanks and I'll follow-up asap

**Comment by polygon** [comment]
Closing this to do some cleanup.
