### ISSUE TITLE
Click is required prerequsite

### ISSUE THREAD

**Issue by ghost** [polygon/spectrum_painter#2]
I needed to run "pip install Click" (under Debian) before "python spectrum_painter/img2iqstream.py --help" would work..

Otherwise I get the following error:
$ python spectrum_painter/img2iqstream.py --help
Traceback (most recent call last):
  File "spectrum_painter/img2iqstream.py", line 1, in <module>
    import click
ImportError: No module named click
$

**Comment by polygon** [comment]
I'll add a note to the documentation regarding dependencies. Thanks for pointing that out.

**Comment by ghost** [comment]
Thanks
