### ISSUE TITLE
Spectrum Painter block missing 

### ISSUE THREAD

**Issue by Kevin1809** [polygon/spectrum_painter#3]
Hello, 
I have installed spectrum_painter and its dependencies in ubuntu 18.04. But when I run Paint_tx.grc in gnu radio companion, it is still missing couple of blocks as shown in attached image. 
Can you help me out? 
![paint_tx grc](https://user-images.githubusercontent.com/38266025/43231180-320d08e4-9063-11e8-993f-d7b43c233590.png)

**Comment by polygon** [comment]
I must have missed this in my notifications, but better late than never.

Unfortunately, I cannot help you with this. The spectrum painter for GNURadio is a separate project from this. I think you need to install the following project instead: https://github.com/drmpeg/gr-paint

**Comment by polygon** [comment]
Closing this to do some cleanup.
